services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/proxy/conf.d:/etc/nginx/conf.d
      - ./docker/proxy/ssl:/etc/nginx/ssl
    depends_on:
      - open-webui