apiVersion: apps/v1
kind: Deployment
metadata:
  name: hurricane-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hurricane-server
  template:
    metadata:
      labels:
        app: hurricane-server
    spec:
      containers:
      - name: hurricane-server
        image: hurricane-server:local         # Use the local image
        ports:
        - containerPort: 8000                 # Expose port 8000 inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: hurricane-server
spec:
  selector:
    app: hurricane-server
  ports:
    - protocol: TCP
      port: 8000                             # External port (Kubernetes cluster)
      targetPort: 8000                       # Container port (within the pod)
  type: NodePort                             # Expose service to external traffic
